# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
use_frameworks!

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'CenteredCollectionView', :path => '../'

  # Pods for Example

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
