name: CI

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        xcodebuild clean test -workspace Example/CenteredCollectionView.xcworkspace -scheme CenteredCollectionView CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
